vpc_cidr_block       = "10.0.0.0/16"
subnet_cidr_block    = "10.0.1.0/24"
availability_zone    = "us-east-1a"
vpc_name             = "dev-vpc"
ami_id               = "ami-0c55b159cbfafe1f0"
instance_type        = "t2.micro"
key_name             = "dev-key-pair"
ec2_name             = "dev-ec2"
