# .github/workflows/terraform.yml
name: Terraform Deploy

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        run: |
          cd environments/${{ github.ref_name }}
          terraform init

      - name: Plan Terraform
        run: |
          cd environments/${{ github.ref_name }}
          terraform plan -out=tfplan

      - name: Apply Terraform
        run: |
          cd environments/${{ github.ref_name }}
          terraform apply -auto-approve tfplan
