name: terraform destroy
on:
    workflow_dispatch: # Trigger the workflow manually
jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: latest
            
            - name: Terraform Init
              run: |
                cd terraform-repo/environments/dev
                terraform init

            - name: Terraform Destroy
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                cd terraform-repo/environments/dev
                terraform destroy -auto-approve


              
              

