name: Terraform Deployment to AWS

on:
  push:
    branches:
      - Dev  # Trigger deployment when code is pushed to 'prod' branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Set your preferred region

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.0'  # Set the required version of Terraform

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform deployment
        run: terraform plan -var-file=terraform.tfvars

      - name: Apply Terraform deployment
        run: terraform apply -auto-approve -var-file=terraform.tfvars
