name: Terraform Deployment to AWS

on:
  workflow_dispatch: # Trigger the workflow manually
  # push:
  #   branches:
  #     - Dev  # Trigger deployment when code is pushed to 'prod' branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Set your preferred region

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.0'  # Set the required version of Terraform

      - name: Terraform Init
        run: |
          cd terraform-repo/environments/dev  # Navigate to the dev environment directory
          terraform init  # Initialize Terraform configuration

      - name: Terraform Plan
        run: |
          cd terraform-repo/environments/dev
          terraform plan -var-file=terraform.tfvars  # Generate and show an execution plan

      - name: Terraform Apply
        run: |
            cd terraform-repo/environments/dev
            terraform apply -auto-approve -var-file=terraform.tfvars  # Apply the changes automatically without asking for confirmation